1. solved the problem :
23. error about declaration of functions.
        What g++ needs to see is an error for ".L myMacro.C"
-->
        Error: Redefinition of default argument systemUtils.h:44:

I had a header file with functions. Both the declaration and implementation of a function was in that file and some functions were taking default arguments. One way of declaring functions was necessary for g++ compilation. But this declaration was giving error for ".L myMacro.C" .
    ==> default argument for a function should be specified in the function declaration. Default argument should not be in function implementation.
            Ex. :
std::vector<string> getFileNames(const char* dirname=".", const char* ext="");
...
std::vector<string> getFileNames(const char* dirname, const char* ext)
{
...
}

        What I did before which was working with "g++", but giving errors with ".L myMacro.C" :
std::vector<string> getFileNames(const char* dirname, const char* ext);
...
std::vector<string> getFileNames(const char* dirname=".", const char* ext="") {
...
}

http://stackoverflow.com/questions/9260246/function-default-arguments-and-headers
http://stackoverflow.com/questions/1440222/constructors-with-default-parameters-in-header-files
http://stackoverflow.com/questions/14902129/default-parameters-in-h-and-cpp-files
http://stackoverflow.com/questions/2842928/default-value-of-function-parameter